### PR TITLE
XDR-1750: Create sysmon-config repository

### PR DESCRIPTION
**Pull request by hensonto**

### CODE REVIEW

**Comment by hensonto** [comment]
@arledesma I added pre-commit and pipeline config to this fork but I might need your help tomorrow to onboard this to our pipeline

**Comment by hensonto** [comment]
After talking to @lukiffer there are additonal things I would need to check. Adding `WIP`

**Comment by hensonto** [comment]
Remove `WIP` this PR is open for review again

**Review by GerardSetho — APPROVED** [review]
Looks good.

**Comment by hensonto** [comment]
Thanks @GerardSetho I will add this to the pipeline then fingers cross

**Pull request merged**
